title:            archerabi.com
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          Abhijith Reddy
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: 'UA-44692445-1'

links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/archerabi
    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

